See previous commit message
 - renamed ldap specific jobs so that they do not include the shibboleth.idp prefix anymore
 - modified all templates do download java8 in a cleaner manner.
 - moved the IdP configurations section awasy from centos7-shibboleth-idp template into the
   shibboleth.idp.setup job
 - reuploaded all the other job configurations as well because of some formatting issues:
	&#13;   should be    &#xd;
	"	should be    &quot;

diff --git a/templates/centos7-shibboleth-idp b/templates/centos7-shibboleth-idp
--- a/templates/centos7-shibboleth-idp
+++ b/templates/centos7-shibboleth-idp
@@ -8,10 +8,9 @@ CATALINA_HOME="/usr/share/tomcat"
 TOMCAT_CONF="/etc/tomcat/tomcat.conf"
 TOMCAT_CONF_DIR="${CATALINA_HOME}/conf"
 
-SHIB_FILE="shibboleth-identity-provider-3.1.2.tar.gz"
-SHIB_DIR="shibboleth-identity-provider"
+SHIB_LATEST="http://shibboleth.net/downloads/identity-provider/latest/"
 SHIB_INSTALL_DIR="/opt/shibboleth-idp"
-SHIB_INSTALL_PROPERTIES="`pwd`/shib.properties"
+SHIB_DIR="/opt/shibboleth-install"
 
 ######################################################################################
 # General config and utils                                                           #
@@ -34,13 +33,16 @@ hostname `hostname -s`.demo
 
 
 # installing java 8
-wget -q --no-cookies --no-check-certificate \
-	--header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F;   \
-        oraclelicense=accept-securebackup-cookie" \
-        "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jdk-8u45-linux-x64.rpm"
-rpm -iv jdk-8u45-linux-x64.rpm
-echo "export JAVA_HOME=${JAVA_HOME}" >> /etc/bashrc
-echo 'export PATH=${JAVA_HOME}/bin:${PATH}' >> /etc/bashrc
+JAVA_LINK=`curl -s http://www.java.com/en/download/linux_manual.jsp 2>/dev/null | grep -m 1 'Linux x64 RPM'| cut -d '"' -f 4`
+if [ -n $JAVA_LINK ]; then
+        wget -q -O sun-java.rpm ${JAVA_LINK}
+        rpm -iv sun-java.rpm
+        echo "export JAVA_HOME=${JAVA_HOME}" >> /etc/bashrc
+        echo 'export PATH=${JAVA_HOME}/bin:${PATH}' >> /etc/bashrc
+else
+        echo "Could not find the right JAVA_LINK"
+        exit 1;
+fi
 
 # installing tomcat
 yum -y install tomcat
@@ -66,71 +68,22 @@ sed -i "s#^JAVA_HOME=.*#JAVA_HOME=\"${JAVA_HOME}\"#"  ${TOMCAT_CONF}
 
 
 # download and unpack shibboleth idp v3
-wget -q http://shibboleth.net/downloads/identity-provider/latest/${SHIB_FILE}
-mkdir ${SHIB_DIR}
-tar xzf ${SHIB_FILE} -C ${SHIB_DIR}
-mkdir ${SHIB_INSTALL_DIR}
+SHIB_FILE=`curl -s ${SHIB_LATEST} | grep tar.gz\< | cut -d '"' -f 6`
 
-# create idp.merge.properties file
-cat > "${SHIB_INSTALL_PROPERTIES}" <<EOF
-idp.sealer.storePassword= changeit
-idp.sealer.keyPassword= changeit
-idp.entityID= https://`hostname`/idp/shibboleth
-idp.scope= `domainname`
-EOF
-
-# install shibboleth 
-pushd ${SHIB_DIR}/*/
-./bin/install.sh  -Didp.src.dir=. \
-                       -Didp.target.dir="${SHIB_INSTALL_DIR}" \
-                       -Didp.merge.properties="${SHIB_INSTALL_PROPERTIES}" \
-                       -Didp.host.name=`hostname` \
-                       -Didp.scope=`domainname` \
-                       -Didp.sealer.password="changeit" \
-                       -Didp.keystore.password="changeit"
-popd
-
-# setting up tomcat for shibboleth idp
-# tomcat will find the .war to deploy by this config file
-cat > ${CATALINA_HOME}/conf/Catalina/localhost/idp.xml <<EOF
-<Context docBase="${SHIB_INSTALL_DIR}/war/idp.war"
-               privileged="true"
-               antiResourceLocking="false"
-               swallowOutput="true" />
-EOF
-
-# define idp.home for tomcat
-sed -i "s/CATALINA_OPTS=.*/CATALINA_OPTS='-Xmx512m -XX:MaxPermSize=128m -Didp.home=\/opt\/shibboleth-idp\'/" ${TOMCAT_CONF}
-# downalod jstl support
-wget -q https://build.shibboleth.net/nexus/service/local/repositories/thirdparty/content/javax/servlet/jstl/1.2/jstl-1.2.jar -O ${CATALINA_HOME}/lib
-# disable session persistence in tomcat
-if [ -z "`xmlstarlet sel -T -t -i "/Context/Manager" -o exists ${TOMCAT_CONF_DIR}/context.xml`" ]; then
-	xmlstarlet ed -L -s "/Context" --type elem -n "Manager"  \
-		-i "//Manager" -t attr -n "pathname" -v "" \
-		 ${TOMCAT_CONF_DIR}/context.xml 
+if [ -n ${SHIB_FILE} ]; then
+        wget -q -O ${SHIB_FILE} "${SHIB_LATEST}${SHIB_FILE}"
+        mkdir ${SHIB_DIR}
+        tar xzf ${SHIB_FILE} -C ${SHIB_DIR}
+        mkdir ${SHIB_INSTALL_DIR}
+else
+        echo "Could not find the right SHIB_FILE"
+        exit 1;
 fi
-# give permission to tomcat over the shibboleth installation
-chown -R tomcat:tomcat ${SHIB_INSTALL_DIR}
-# change the java version used in JSP compilation to 1.7 (1.6 is not supported anymore)
-if [ -z `xmlstarlet sel -T -N x="http://java.sun.com/xml/ns/javaee" -t \
-	-i "/x:web-app/x:servlet[x:servlet-name='jsp']/x:init-param[x:param-name='compilerSourceVM']" \
-	-o exists -n ${TOMCAT_CONF_DIR}/web.xml` ]; then
-	
-	xmlstarlet ed -L -N x="http://java.sun.com/xml/ns/javaee" \
-	   	-s "/x:web-app/x:servlet[x:servlet-name='jsp']" --type elem -n "init-param-tmp" \
-		-s //init-param-tmp --type elem -n "param-name" -v "compilerSourceVM" \
-		-s //init-param-tmp --type elem -n "param-value" -v "1.7" \
-		-r //init-param-tmp -v "init-param" ${TOMCAT_CONF_DIR}/web.xml
 
-fi
-if [ -z `xmlstarlet sel -T -N x="http://java.sun.com/xml/ns/javaee" -t \
-	-i "/x:web-app/x:servlet[x:servlet-name='jsp']/x:init-param[x:param-name='compilerTargetVM']" \
-	-o exists -n ${TOMCAT_CONF_DIR}/web.xml` ]; then
-	
-	xmlstarlet ed -L -N x="http://java.sun.com/xml/ns/javaee" \
-	   	-s "/x:web-app/x:servlet[x:servlet-name='jsp']" --type elem -n "init-param-tmp" \
-		-s //init-param-tmp --type elem -n "param-name" -v "compilerTargetVM" \
-		-s //init-param-tmp --type elem -n "param-value" -v "1.7" \
-		-r //init-param-tmp -v "init-param" ${TOMCAT_CONF_DIR}/web.xml
 
-fi
+######################################################################################
+# LDAP Server                                                                        #
+######################################################################################
+
+yum -y install openldap openldap-clients openldap-servers
+
